# Generated by Django 5.2.8 on 2025-12-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
