services:
  db:
    image: postgres:16-alpine
    container_name: online_school_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: online_school_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    container_name: online_school_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    container_name: online_school_celery
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: celery -A config worker -l info

  celery-beat:
    build: .
    container_name: online_school_celery_beat
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: celery -A config beat -l info
    volumes:
      - celerybeat_data:/app/celerybeat

volumes:
  postgres_data:
  redis_data:
  celerybeat_data:
